# Install uv
FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.5.11 /uv /uvx /bin/

# Change the working directory to the `app` directory
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Copy the project into the image
ADD ./.env /app/.env
ADD ./pyproject.toml /app/pyproject.toml
ADD ./config /app/config
ADD ./mlruns /app/mlruns
ADD ./packages /app/packages
ADD ./api /app/api

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --group=api

# Add venv ao path
ENV PATH="/app/.venv/bin:$PATH"
ENTRYPOINT []

EXPOSE 8000

CMD ["python", "api/main.py"]
