alias: null
batch_size: 32
check_val_every_n_epoch: 100
context_size: 10
dataloader_kwargs: null
decoder_hidden_size: 64
decoder_layers: 2
drop_last_loader: false
early_stop_patience_steps: -1
encoder_bias: true
encoder_dropout: 0.0
encoder_hidden_size: 300
encoder_n_layers: 1
futr_exog_list: null
h: 77
hist_exog_list: null
inference_input_size: -1
input_size: 4928
learning_rate: 0.008279309926218455
loss: !!python/object:src.utils.WMAPE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters: {}
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 10000
num_lr_decays: -1
num_workers_loader: 0
optimizer: null
optimizer_kwargs: null
random_seed: 19
scaler_type: robust
stat_exog_list: null
val_check_steps: 100
valid_batch_size: null
valid_loss: null
